# -*- coding: utf-8 -*-
"""DL : Ex 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPrstDBKTuQ9sjpkrR6gWYQcVgvfysH4
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

model = Sequential()
model.add(Dense(4, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500, batch_size=1, verbose=1)
loss, accuracy = model.evaluate(X, y, verbose=0)
print(f"\nAccuracy: {accuracy * 100:.2f}%")
predictions = model.predict(X)
print("\nPredictions:")
print(np.round(predictions))